export const copy = {
  common: {
    cancel: 'Annuler',
    save: 'Enregistrer',
    createItem: 'Créer un item',
    allCategories: 'Toutes catégories',
    allTypes: 'Tous les types',
  },
  itemForm: {

    labels: {
      name: 'Nom',
      category: 'Catégorie',
      type: 'Type',
      weaponId: 'ID (arme)',
      image: 'Image (copier/coller ou PNG/JPEG)',
      buyPrice: 'Prix achat',
      sellPrice: 'Prix vente',
      initialStock: 'Stock initial',
      description: 'Description',
      unifiedSubtitle: 'Formulaire unifié',
    },
    sections: {
      infos: 'Infos',
      economy: 'Économie',
      stock: 'Stock',
    },
    fields: {
      name: 'Nom *',
      category: 'Catégorie *',
      type: 'Type *',
      internalId: 'ID interne (unique)',
      description: 'Description',
      buyPrice: 'Prix achat',
      sellPrice: 'Prix vente',
      internalValue: 'Valeur interne',
      stockInitial: 'Stock initial',
      stockLow: 'Seuil stock bas',
      weight: 'Poids',
      maxStack: 'Max stack',
    },
    toggles: {
      showInFinance: 'Afficher dans Finance',
      active: 'Actif',
      stackable: 'Empilable',
    },
    errors: {
      createFailed: 'Impossible de créer l’item.',
      nameRequired: 'Le nom est obligatoire.',
      typeRequired: 'Le type est obligatoire.',
    },
  },
  finance: {

    stockFlow: {
      stockOutTitle: 'Sortie du stock',
      stockOutSubtitle: 'Sortie des items du stock par les membres pour des raisons diverses.',
      stockOutReasonRequired: 'Raison obligatoire pour une sortie de stock.',
      stockOutSaved: 'Sortie de stock enregistrée.',
      stockOutModeLabel: 'Sortie',
      stockInTitle: 'Entrée du stock',
      stockInSubtitle: 'Entrée des items en stock par les membres pour des raisons diverses.',
      stockInReasonRequired: 'Raison obligatoire pour une entrée de stock.',
      stockInSaved: 'Entrée de stock enregistrée.',
      stockInModeLabel: 'Entrée',
      stockInOutButton: 'Entrée / Sortie',
    },

    trade: {
      title: 'Achat / Vente (Items)',
      subtitle: 'Formulaire unifié',
      modeBuy: 'Achat',
      modeSell: 'Vente / Sortie',
      typeOptional: 'Type (optionnel)',
      selectedItem: 'Item sélectionné',
      stockNow: 'Stock actuel',
      noItem: 'Aucun item sélectionné',
      saveInProgress: 'Validation…',
    },
    actions: {
      buy: 'Achat',
      sell: 'Vente / Sortie',
      validate: 'Valider',
    },
    labels: {
      counterparty: 'Interlocuteur',
      notes: 'Notes',
      paymentMode: 'Mode de paiement',
      quantity: 'Quantité',
      unitPrice: 'Prix unitaire (override)',
      total: 'Total',
      item: 'Item *',
      category: 'Catégorie',
    },
    errors: {
      loadItemsFailed: 'Impossible de charger les items.',
      saveFailed: 'Impossible d’enregistrer la transaction.',
      stockInsufficient: 'Stock insuffisant pour cette vente/sortie.',
      loadFailed: 'Impossible de charger la finance.',
    },
    toastSaved: 'Transaction enregistrée.',
  },
} as const
